title: Evan Trock  # your name (or website title) here
logo: "/images/HeadshotReal.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.linkedin.com/in/EvanTrock/">LinkedIn</a> 
  <br>
  <a href="https://docs.google.com/document/d/1WGRZtIPCLO7zAmKNxWoGAnjWkk_IZ8Du4qhva4sqx5E/edit?usp=sharing" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://www.GitHub.com/EvanTLeh/">GitHub</a>  

theme: jekyll-theme-minimal
